### ISSUE TITLE
create github scripts for checkin/branching etc

### ISSUE THREAD

**Issue by va3wam** [va3wam/TWIPe#88]
Write scripts to do the git commands that we use from our version control Wiki page.

**Comment by nerdoug** [comment]
bash scripts are in the new bash subdirectory for these actions: 
   git-new-branch.sh <branch-name>     // to create a brand new branch
   git-pull-request.sh <branch-name>     // for pull preparation done in CLI
   git-delete-branch.sh <branch-name>   // for post merge branch cleanup

**Comment by nerdoug** [comment]
Would be interesting to do the full pull/merge process from a script, and not require you to go into a browser session to complete the merge. Should be doable, so I'm tagging that onto this task.
